apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
  - name: metallb
    namespace: metallb-system
    releaseName: metallb
    includeCRDs: true
    version: 0.15.3
    repo: https://metallb.github.io/metallb

resources:
  - ippool.yaml
  - l2adver.yaml

namespace: metallb-system