apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
  namespace: cert-manager
type: kubernetes.io/tls
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIUHm6AnfEEYQdZWcDezLnycNcrK4owDQYJKoZIhvcNAQEL
    BQAwIjEgMB4GA1UEAxMXTWFsZWZTdG9ybSBJbmMuIFJvb3QgQ0EwHhcNMjYwNDA0
    MTEwODU4WhcNMjYwNzAzMTEwODU4WjAiMSAwHgYDVQQDExdNYWxlZlN0b3JtIElu
    Yy4gUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMctFlew
    ABN2biFuwAhQlJ5giVrEaACuKwcXZ5PEA12o8SZIihdR5MAyjojsohQYHkjbPLrX
    4+l1lYopjXlfadEhkrturIIqX0yfKywh2H6EhNkrm5KFreIXHdAsqYe9Ta+GFYZO
    xOkobbp7PAl4z9qitYQbskWJN5qOSXCRJfwIvdbS0pFvw+u2bYiQg8Rb2QgjN1v0
    2hZp974W7rcMW2qCRy8kvrB1m04Tj+jqCjwwX75ZkaYrqmLRGk83mLpQygLEw4yj
    ibT1DuCb6Newm1Mnyn2iq02ZYa3W0S+nciewgTENEAUIZ515VuAuin+YDCc5uepG
    lIOqskzuEJoOURkCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFCSgXx39HCLURcYb4kCikPX3WusrMA0GCSqGSIb3DQEB
    CwUAA4IBAQAovqXVcKk1+WlpDv8aoOXwCY9oWSJvF1oOz9H0wnd9IyhDxr3bC8V9
    TsbEN2E9WFaDkom6X8H9DCGYe7InTjQ5BOaU9/4iyRy5cZ2/lYTcCokvTlVfzN5A
    jKT3OuCSW875VpJJEsa5kT9/XrTucgrBSGaF6/QVgcymxwh2f0HyfHoBvEQLfb/w
    88EHJeQPdBHme4IgqcN4XzayRQVpnxJGFBUkqFgxDFVNhfif7iHAY7qEProV+ses
    yoXUgSLGPi0BKsmomSGfjmxKCnIqQPfYKEiPmh9KtAf9ZmS8kXD8+krsXlNEKO9a
    QIkfDBqFjDr9GNDYw3Qtoc1Z8d/sJMk0
    -----END CERTIFICATE-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIUHm6AnfEEYQdZWcDezLnycNcrK4owDQYJKoZIhvcNAQEL
    BQAwIjEgMB4GA1UEAxMXTWFsZWZTdG9ybSBJbmMuIFJvb3QgQ0EwHhcNMjYwNDA0
    MTEwODU4WhcNMjYwNzAzMTEwODU4WjAiMSAwHgYDVQQDExdNYWxlZlN0b3JtIElu
    Yy4gUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMctFlew
    ABN2biFuwAhQlJ5giVrEaACuKwcXZ5PEA12o8SZIihdR5MAyjojsohQYHkjbPLrX
    4+l1lYopjXlfadEhkrturIIqX0yfKywh2H6EhNkrm5KFreIXHdAsqYe9Ta+GFYZO
    xOkobbp7PAl4z9qitYQbskWJN5qOSXCRJfwIvdbS0pFvw+u2bYiQg8Rb2QgjN1v0
    2hZp974W7rcMW2qCRy8kvrB1m04Tj+jqCjwwX75ZkaYrqmLRGk83mLpQygLEw4yj
    ibT1DuCb6Newm1Mnyn2iq02ZYa3W0S+nciewgTENEAUIZ515VuAuin+YDCc5uepG
    lIOqskzuEJoOURkCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFCSgXx39HCLURcYb4kCikPX3WusrMA0GCSqGSIb3DQEB
    CwUAA4IBAQAovqXVcKk1+WlpDv8aoOXwCY9oWSJvF1oOz9H0wnd9IyhDxr3bC8V9
    TsbEN2E9WFaDkom6X8H9DCGYe7InTjQ5BOaU9/4iyRy5cZ2/lYTcCokvTlVfzN5A
    jKT3OuCSW875VpJJEsa5kT9/XrTucgrBSGaF6/QVgcymxwh2f0HyfHoBvEQLfb/w
    88EHJeQPdBHme4IgqcN4XzayRQVpnxJGFBUkqFgxDFVNhfif7iHAY7qEProV+ses
    yoXUgSLGPi0BKsmomSGfjmxKCnIqQPfYKEiPmh9KtAf9ZmS8kXD8+krsXlNEKO9a
    QIkfDBqFjDr9GNDYw3Qtoc1Z8d/sJMk0
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAxy0WV7AAE3ZuIW7ACFCUnmCJWsRoAK4rBxdnk8QDXajxJkiK
    F1HkwDKOiOyiFBgeSNs8utfj6XWViimNeV9p0SGSu26sgipfTJ8rLCHYfoSE2Sub
    koWt4hcd0Cyph71Nr4YVhk7E6Shtuns8CXjP2qK1hBuyRYk3mo5JcJEl/Ai91tLS
    kW/D67ZtiJCDxFvZCCM3W/TaFmn3vhbutwxbaoJHLyS+sHWbThOP6OoKPDBfvlmR
    piuqYtEaTzeYulDKAsTDjKOJtPUO4Jvo17CbUyfKfaKrTZlhrdbRL6dyJ7CBMQ0Q
    BQhnnXlW4C6Kf5gMJzm56kaUg6qyTO4Qmg5RGQIDAQABAoIBAAybhKNojTquJ463
    dFGaayviw7MChWxMmgXlA/4JHWbtcZVJKG+NNB/720ScyO4hcDJPqVaQ4Zj2o9B2
    7KD7CodNuxxg5yvGm5ltplWQ72OjxwZ5oYt66XyrFqyllRYV5B/ZCo4BuKpjEB4K
    nKxjULHf1IJQH/7RjpraiJjG4UsElF+wTq32VLZqdQp58/2S7DKfwh0wsAFnpm3T
    m/ZcQzysolOnhyuZGC8wA72xNWzGDCq1SlJ2gfTaP/nYbAtG+DagHPO6RKU7C6NU
    9Fk0TaOIp3zu5UGJ8B7NNlnUJtl9KVlkQ2vIAoYDDZihHjfCHwlTvhivzQicIwY3
    NwNChmECgYEAyi1GNmlKLaGy0x/3T+gGTYd2RaTPnsQygASyc7ikFlOiZCDnF+nM
    grFqTeFarLEjVFvSQGoFnOFU+U828H/Edr24m8KtJdQ4KjfRoRIGW5wYZcYHQM7X
    8/nAHEK8GFRsxXvFLYJ2+WXZ/aMyyUmxhUP5OJcdcDGXFYhxqJlYSzkCgYEA/DNO
    xLMegK7K/mhSNMraKQw24GSsX89Liqu+i4yy40YTcElQmY3slS5hE3S04tj4a9it
    QJKjp6UoDvGVfM98kQFwPujT1QhaKfHzUJBYXEgnvqfNBRe9ieP8l/cQGqnFYeZp
    QkJsgjPadgHjxC4ocmMvQv5UePR1Vrgk+olx1OECgYAsDLc6jbA6xvtWYqWYxF3z
    MGuFewY9elPibqOO8RDXSHueQ0j2fdswMoWN2GbQL3waGjNyE2eLqdDAzRCUT9I3
    aNi7HyxojJd8I1NKO8ok1Zq/OelEpoyIvMatoaCn0GUulev9IWrYpedcCt2625KR
    DaFUQiCI3FUlvOe+q0KAiQKBgBnmAu68HiPEz1+0wsxdEG4qrO/6JqFoHi/NVzHp
    bu1b4t8jCD3cjzD6pEllMLYi5c/dXl1FMb0jfquaL2mzvOz/ItGzAx3bT7cC+6OI
    Tyqa1koD3U/qkjI40VWhr2uth3F4QdLmE1KDlKmNpCAfRVQJz26nw3DwWaRgIJwB
    xUjBAoGBAMLx3jPctPTqri2Sgzt69XvIn6T2VS8ArjlpwRp0XOUzv2YfRhtWP7y3
    8ReAO4dsaut1aArz1mLdhO23suG98UFAW/xof8sIstcCPd/CN9yvJJRqTngvqoyj
    EN8m/4Sx4Id2UQ0Klo8vskO8gTTZ08FpgQJq6gs5abBOcDjMARNj
    -----END RSA PRIVATE KEY-----
