apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.cluster.local"
    namespace: argocd
  sources:
    - repoURL: https://github.com/LeoEliot/kubernetes
      targetRevision: HEAD
      path: apps/
      directory:
        recurse: true
        include: '**/app.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true