apiVersion: v2
name: kube-prometheus-stack
description: Kube Prometheus Chart
version: 0.1.0
type: application
dependencies: 
  - name: kube-prometheus-stack
    version: 82.15.1
    repository: https://prometheus-community.github.io/helm-charts
