---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: external-dns
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    provider:
      name: rfc2136
    fullnameOverride: external-dns
    policy: sync
    registry: txt
    txtOwnerId: k8s
    txtPrefix: external-dns-
    sources:
      - service
      - crd
    extraArgs:
    - "--rfc2136-host=192.168.1.10"
    - "--rfc2136-port=53"
    - "--rfc2136-zone=malef.lan"
    - "--rfc2136-tsig-secret=SP0tjHmNb+HdGHsQWHftCt4EQ7lMLxfIHZu1W4jhhx8="
    - "--rfc2136-tsig-secret-alg=hmac-sha256"
    - "--rfc2136-tsig-keyname=tsig-key"
    - "--rfc2136-tsig-axfr"