---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: metallb
      version: 0.15.3
      sourceRef:
        name: metallb
        kind: HelmRepository
        namespace: metallb-system
  values:
    crds:
      enabled: true
      keep: false