apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  source:
    repoURL: https://github.com/LeoEliot/kubernetes
    targetRevision: HEAD
    path: manifests/metallb/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true # Recommended to handle webhooks